local M = {}
M.TITLE = "TITLE"
M.INSTRUCTIONS = "INSTRUCTIONS"
M.IN_PLAY = "IN_PLAY"
M.CONFIRM_QUIT = "CONFIRM_QUIT"
M.DEAD = "DEAD"
M.INVENTORY = "INVENTORY"
M.FIGHT = "FIGHT"
M.ATTACK = "ATTACK"
M.STATUS = "STATUS"
M.HIPPIE = "HIPPIE"
M.VENDOR = "VENDOR"
return M